### ISSUE TITLE
Add URL equivalent to `$bal_library_dir `

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-Manager-BAL#86]
## What

Add `$bal_library_dir` that expands to a (percent encoded) file URL pointing to the library directory

## Why

This allows the library dir to be used in locatableContent trait location properties that must be a valid, URL-encoded file URL instead of a path. Presently, if the path to the library contains spaces or other non-URL-legal characters, then BAL will return invalid data when `$bal_library_dir` is used in trait properties that are required to be a URL.

## ACs

* `file://$bal_library_url/file.ext` -> `file://c:/path/to/lib/file.ext` (Windows) `file:///path/to/lib/file.ext` (POSIX)
* Path should be normalised: `file://$bal_library_url/../file.ext` -> `file://c:/path/to/file.ext` (Windows) `file:///path/to/file.ext` (POSIX)
* URL should be `FileUrlPathConverter::pathFromUrl` compatible (e.g. check UNC paths).
* `bal_library_dir_url` should also be supported
* Normalization behaviour should be triggered based on whether the data is a file url.
* Try very hard to avoid using openassetio utils in BAL backend.

**Comment by elliotcmorris** [comment]
This thing might be pretty good for testing host integrations.

**Comment by feltech** [comment]
This came up recently as a blocker for automated testing of a real-world integration.
