### ISSUE TITLE
Support entity access policies

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO-Manager-BAL#90]
## What

Allow the BAL library to define that specific entities are read-only/write only and disallow publishing

## Why

Allows that branch of OpenAssetIO api contracts to be tested

## ACs

- By default, `resolve` and `entityTraits` treats all access modes the same as the current happy path (i.e. `read`).
- Exceptions can be added for explicit access modes that override the data in the versions list. This applies to all entity trait queries.
- An exception for an access mode that maps to `null` disables that access mode, with appropriate errors raised.
- Publishing methods (`preflight` and `register`) error based on management policy.
- Publishing methods (`preflight` and `register`) error based on entity traits with `write` policy.
- Update https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/69

**Comment by foundrytom** [comment]
The main idea here is that making existing entities read-only per-se is prohibitive, and not a pattern we want to encourage (imaging opening a work file, making a change, then republishing). If you couldn't just republish to the existing entity, you'd need some overly complex `getWithRelationship` dance.

**Comment by feltech** [comment]
Note that a prior addition to support access  modes has #98 a bug, in that `supported_access_modes` does not propagate to newly published versions, so once an entity is published it becomes read-only.

It's likely this existing mechanism will be rewritten as part of this issue, so not creating a separate bug report.
